[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "."
  
  # Default build command
  command = ""

[functions]
  # Directory with serverless functions
  directory = "netlify/functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
